### ISSUE TITLE
Escribir textos para mails de invitación

### ISSUE THREAD

**Issue by spalladino** [instedd/cruzroja-registro#24]
Actualmente están los defaults de invitable

**Comment by juanedi** [comment]
Idem para restauración de contraseña.

**Comment by vtiffenberg** [comment]
Texto para invitación:
"Bienvenido. Fuiste ingresado al sistema de Cruz Roja Argentina. Para terminar el proceso y sacar tu cuenta, por favor usá el siguiente enlace.
_Crear mi cuenta_
¡Muchas gracias!"

**Comment by vtiffenberg** [comment]
Texto para reseteo de contraseña:
"¡Hola Raquel!
Se hizo un pedido de cambio de contraseña en tu cuenta. Podés generar una nueva con el enlace acá abajo:
_Resetear mi contraseña_
Si vos no pediste este cambio, ignorá el mail.
Tu contraseña no se va a modificar a menos que accedas al enlace."

**Comment by vtiffenberg** [comment]
![screen shot 2017-01-24 at 3 21 59 pm](https://cloud.githubusercontent.com/assets/4836220/22260671/cd0483ec-e248-11e6-8414-6e45b5c4bf96.png)

**Comment by vtiffenberg** [comment]
Aceptado: 
<img width="1012" alt="screen shot 2017-01-25 at 9 57 11 am" src="https://cloud.githubusercontent.com/assets/4836220/22291377/e0ab1df6-e2e4-11e6-8e8c-c9c5c58430ed.png">

Rechazado:
<img width="1004" alt="screen shot 2017-01-25 at 9 59 25 am" src="https://cloud.githubusercontent.com/assets/4836220/22291395/f650df7e-e2e4-11e6-8b49-9fc3ab027c34.png">

Estos textos estaría bien que los validara alguien de CR
