### ISSUE TITLE
Error de configuración de server SMTP al deployar

### ISSUE THREAD

**Issue by juanedi** [instedd/cruzroja-registro#40]
Tras hacer un deploy, la aplicación no puede mandar emails. Al intentar, por ejemplo, resetear un password se loguea que la configuración es inválida porque falta setear algunas variables.

Para que funcione es necesario:

- entrar al container
- ejectuar `mix clean && mix compile`
- reiniciar el container

Parecería ser que el template `prod.exs` se está hidratando antes de que estén seteadas las variables. De cualquier forma, es extraño que esto no funcione pero las settings de base de datos sí.

**Comment by waj** [comment]
Ya le comenté a @juanedi verbalmente, pero for the record, en Ask nos encontramos con el mismo problema y este es el cambio que hay que hacer: https://github.com/instedd/ask/commit/fda025bd21f90630ca32031191f620764d778050

**Comment by waj** [comment]
https://github.com/swoosh/swoosh/blob/21e475a5bb4e0ebb6206d6e09762f606078d32d8/lib/swoosh/mailer.ex#L28-L30
