### ISSUE TITLE
Workflow de aprobación

### ISSUE THREAD

**Issue by spalladino** [instedd/cruzroja-registro#6]
Al darse de alta, eligiendo su filial y si requiere alta como voluntario o como asociado, un usuario se encuentra pendiente de aprobación. Un administrador de filial debe poder marcarlo como *aprobado* o *rechazado*. De ser aprobado, el usuario tiene acceso a más campos a completar en su perfil.

Toda transición dispara un mail al usuario.

**Comment by spalladino** [comment]
Pregunta: el segundo formulario, debe ser también validado?

**Comment by juanedi** [comment]
Cierro este ticket. El envío de mails se trackea por separado en https://github.com/instedd/cruzroja-registro/issues/20.
