### ISSUE TITLE
Agregar campos de actividad de usuario

### ISSUE THREAD

**Issue by spalladino** [instedd/cruzroja-registro#66]
Agregar campos editables por admin de filial y visibles por usuario:

- [x] Actividad por trimestre: generar un campo de texto por cada trimestre **calendario** desde la fecha de unión del voluntario, donde el admin puede cargar las actividades del voluntario; junto a cada campo de texto, agregar un checkbox de "sin actividad", que si está marcado grisa el campo

- [x] Check de pago de cuota de asociado: generar un checkbox por cada mes desde que el usuario es asociado por pago (si es voluntario no mostrarlo) indicando si pagó o no

- [x] Campo de observaciones generales

**Comment by vtiffenberg** [comment]
@spalladino : no termino de entender cómo tiene que funcionar esto, es un campo por trimestre desde el año 87 (si se registró ese año), o del último año?

Y los pagos lo mismo, cuán para atrás hay que ir?

**Comment by spalladino** [comment]
@vtiffenberg hagamoslo desde la fecha en q se registró (intentando no romper la UI si se registro en el 87). Podemos poner los mas recientes arriba. Igual lo dejo taggeado para chequearlo.

**Comment by vtiffenberg** [comment]
Una más: por ahora tenemos una sola fecha de registración, no sabemos cuándo pasó de voluntario a asociado si fuera el caso. Agrego esa fecha?

**Comment by spalladino** [comment]
Dale. Y si va y viene, guardamos sólo la última.

**Comment by vtiffenberg** [comment]
Hay varios flujos distintos en este issue:
- El voluntario que pide pase a asociado (como voluntario debe verse sus campos de actividad, cuando pasa a asociado deben verse los campos de pagos a partir de esa fecha)
- El asociado importado (tomamos como fecha de comienzo la misma que de registración, o sea que las fechas de actividad y pagos van a ser la misma)
- El asociado nuevo, no importado, que se registra (y sus fechas de pago y actividad iniciales también coinciden).
- El voluntario que es modificado por un admin para ser asociado (no pasa por el flujo de pedir el pase). Es igual al primer caso. 

Para QA: Para todos se debería poder agregar/editar/remover cada actividad y cada pago.
