### ISSUE TITLE
Agregar campo de observaciones durante la registración de un usuario

### ISSUE THREAD

**Issue by spalladino** [instedd/cruzroja-registro#72]
Texto plano destinado a que el admin de filial lo lea. Ver si queremos ocultarlo en la pantalla de detalle de perfil una vez ya aprobado.

**Comment by vtiffenberg** [comment]
Agregado al registrase y para el admin que lo apruebe. Después no se ve más, ni en el perfil de usuario, ni para el detalle del admin.
