### ISSUE TITLE
Workflow de transición a asociado

### ISSUE THREAD

**Issue by spalladino** [instedd/cruzroja-registro#8]
Un usuario nuevo o un usuario existente con rol de voluntario debe poder pedir "upgrade" a asociado. Este upgrade debe ser aprobado por un adminsitrador al igual que la registración como voluntario.

**Comment by spalladino** [comment]
Pregunta: la aprobación para asociado es la misma que para voluntario?

**Comment by spalladino** [comment]
Pendiente confirmación, pero puede haber diferencias: ej, asociado debe ser confirmado en central.

**Comment by juanedi** [comment]
Pendiente a definir cómo es el pasaje a asociado **pago**.

Deberíamos diferenciarlo de el asociado que se registró como tal?
Y del que se propone tras un año?

**Comment by vtiffenberg** [comment]
El botón debería estar siempre, va a depender de una persona que lo apruebe verificar si el voluntario ya tiene el beneficio por haber estado un año o si se hizo un pago.

**Comment by juanedi** [comment]
CRA va a darnos algún texto / link para agregar en la pantalla algo de información sobre qué significa esa botón.
