### ISSUE TITLE
No se crea log de actividad al crear una filial con administradores

### ISSUE THREAD

**Issue by juanedi** [instedd/cruzroja-registro#82]
Si creo una filial con administradores, esperaría que en el log de actividad de los usuarios aparezca una entrada del tipo "X fue agregado como administrador de la filial Y".

Este tipo de logs hoy sólo se están creando al actualizar la filial.

**Comment by pmallol** [comment]
En versión 9aca6ee, se registra correctamente que el rol del usuario fue modificado a administrador pero no se especifica la filial. 

> P M lo hizo administrador de una filial el 3/4/2017 a las 20:08

**Comment by vtiffenberg** [comment]
Así es, faltaría esa información, pero queda afuera hasta la próxima iteración que haya.
